# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ad4c543e02a1d384c59c0357cfbf27fa6f6cec242d0696bd749a93e83b811836d50fc5a9ec672c56e7232c9751265519c053b94f73574a4d894f2957a5f4d72

test:
  secret_key_base: cb5b94d75db4b75668c5d891190f1fe77e5c1d7a276cb8acc6f82add516a1abac78bd53a006497d7d81d003f43b87ebfeb6b990eec184038659b25418be2146b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
